//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sitesatis.Models.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int id { get; set; }
        public string product_name { get; set; }
        public string product_content { get; set; }
        public int category_id { get; set; }
        public Nullable<int> cargo_type_id { get; set; }
        public Nullable<int> cargo_id { get; set; }
        public Nullable<int> product_price { get; set; }
        public string prouct_image_path { get; set; }
        public Nullable<int> publisher { get; set; }
        public Nullable<int> product_quantity { get; set; }
        public Nullable<int> repository_id { get; set; }
        public Nullable<System.DateTime> product_add_time { get; set; }
    
        public virtual cargo cargo { get; set; }
        public virtual cargo_type cargo_type { get; set; }
        public virtual category category { get; set; }
        public virtual user user { get; set; }
        public virtual repository repository { get; set; }
    }
}
